"""edit pub_date

Revision ID: 0002ec6da46a
Revises: 98ad224e5705
Create Date: 2018-11-28 08:59:13.718687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0002ec6da46a'
down_revision = '98ad224e5705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pub_date', sa.DateTime(), nullable=True))
    op.drop_column('users', 'put_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('put_date', mysql.DATETIME(), nullable=True))
    op.drop_column('users', 'pub_date')
    # ### end Alembic commands ###
