"""edit items

Revision ID: 3ad74e4b417f
Revises: e673687ba81f
Create Date: 2018-11-27 08:25:45.115063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ad74e4b417f'
down_revision = 'e673687ba81f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('priice', sa.Integer(), nullable=True),
    sa.Column('pointsRequired', sa.Integer(), nullable=True),
    sa.Column('img', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    # ### end Alembic commands ###
