"""add address

Revision ID: 52f1ae68be09
Revises: 5a7359ac72f8
Create Date: 2018-11-27 14:00:31.186931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52f1ae68be09'
down_revision = '5a7359ac72f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchanges',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('item', sa.String(length=128), nullable=True),
    sa.Column('guest', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=129), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exchanges')
    # ### end Alembic commands ###
