"""del address

Revision ID: 54fb8fd8d0da
Revises: 3c6e6379495b
Create Date: 2018-11-27 09:41:46.344821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '54fb8fd8d0da'
down_revision = '3c6e6379495b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchanges', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchanges', sa.Column('address', mysql.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
