"""edit name as guest

Revision ID: 610d4402e0b3
Revises: 8119ab318258
Create Date: 2018-11-27 13:29:05.296040

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '610d4402e0b3'
down_revision = '8119ab318258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchanges', sa.Column('guest', sa.String(length=128), nullable=True))
    op.drop_column('exchanges', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchanges', sa.Column('name', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('exchanges', 'guest')
    # ### end Alembic commands ###
