"""add itemid in exchagne

Revision ID: 681111b604dd
Revises: 6e7cef8bdaaf
Create Date: 2018-11-29 09:11:33.192174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '681111b604dd'
down_revision = '6e7cef8bdaaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchanges', sa.Column('itemid', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchanges', 'itemid')
    # ### end Alembic commands ###
