"""add exchange username

Revision ID: 6e7cef8bdaaf
Revises: b9e72252900c
Create Date: 2018-11-29 08:53:25.258629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e7cef8bdaaf'
down_revision = 'b9e72252900c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchanges', sa.Column('username', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchanges', 'username')
    # ### end Alembic commands ###
