"""add address

Revision ID: 8119ab318258
Revises: 54fb8fd8d0da
Create Date: 2018-11-27 09:42:26.233508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8119ab318258'
down_revision = '54fb8fd8d0da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchanges', sa.Column('address', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchanges', 'address')
    # ### end Alembic commands ###
