"""add mebid

Revision ID: b9e72252900c
Revises: 0002ec6da46a
Create Date: 2018-11-28 09:15:49.304280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9e72252900c'
down_revision = '0002ec6da46a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mebid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mebid')
    # ### end Alembic commands ###
